---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/jzingler/gs-rest-service.git
      branch: feature/add-concourse-pipeline  
  - name: cf-push-packaged-app
    type: cf
    source:
      api: {{cf_api}}
      organization: {{cf_org}}
      space: {{cf_space}}
      username: {{cf_username}}
      password: {{cf_password}}
      skip_cert_check: true
      
jobs:
  - name: package
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/complete/ci/tasks/package.yml       
    - put: cf-push-packaged-app
      params:
        manifest: build-output/manifest.yml