---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: maven   
    
inputs:
  - name: source-code

outputs:
  - name: build-output
  
run:
  path: source-code/complete/ci/tasks/package.sh
 