---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: maven   
    
inputs:
  - name: source-code

outputs:
  - name: build-output
  
caches: 
  - path: source-code/complete/.m2
  
run:
  path: /bin/bash
  args: 
    - source-code/complete/ci/tasks/package.sh
 